epik timer and epik fix to rotating retard
olchyk98/deadmind pull request #32
Opened 2021-04-29 16:40 UTC by k0ded

2021-04-29 17:04 UTC, trilleplay requested changes

2021-04-29 17:04 UTC, trilleplay commented on Assets/Scripts/Timer.cs
> +        }
cringe inverta if condition och returna

2021-04-29 17:04 UTC, trilleplay commented on Assets/Scripts/Timer.cs
> +        TimerStopped.Invoke();
cringe ingen ? check

2021-04-29 17:04 UTC, trilleplay commented on Assets/Scripts/Timer.cs
> +
bro

2021-04-29 17:04 UTC, trilleplay commented on Assets/Scripts/Player/PlayerLook.cs
> +            _rigidbody.angularVelocity = Vector3.zero;
bro om detta är allt som någonsin kommer hända med rigidbodyn varför lagras den

2021-04-29 17:17 UTC, olchyk98 requested changes

2021-04-29 17:17 UTC, olchyk98 commented on Assets/Scripts/Timer.cs
> +    [SerializeField] private float timerStart;
_timerStart
alla privata vars måste va `_...`

2021-04-29 17:17 UTC, olchyk98 commented on Assets/Scripts/Timer.cs
> +    public bool started;
hasStarted bram

2021-04-29 17:17 UTC, olchyk98 commented on Assets/Scripts/Timer.cs
> +    public UnityAction TimerStopped;
OnTimerStopped

2021-04-29 17:17 UTC, olchyk98 commented on Assets/Scripts/Timer.cs
> +    Stopwatch watch = new Stopwatch();
private

2021-04-29 17:17 UTC, olchyk98 commented on Assets/Scripts/Timer.cs
> +    private string pattern = @"HH\:mm\:ss";
_outputPattern

2021-04-29 17:17 UTC, olchyk98 commented on Assets/Scripts/Timer.cs
> +        if (started)
```
if(!started) return;
...
```

2021-04-29 17:17 UTC, olchyk98 commented on Assets/Scripts/Timer.cs
> +            }else if (!countsUp && timerSeconds < timerEnd)
skapa ett annat variable for condition för att ta bort if else
```
var whatever = (countsUp && timerSeconds > timerEnd) ||
(!countsUp && timerSeconds < timerEnd)
```

2021-04-29 17:17 UTC, olchyk98 commented on Assets/Scripts/Timer.cs
> +    private void Update()
`FixedUpdate`.
Update är på varje frame
Vi vill syssla me tiden

2021-04-29 17:32 UTC, k0ded commented on Assets/Scripts/Timer.cs
> +    [SerializeField] private float timerStart;
Nope de är serializefield och ska därför inte ha _ (enligt rider)

2021-04-29 17:33 UTC, k0ded commented on Assets/Scripts/Timer.cs
> +    private void Update()
Med tanke på att detta är något som säkert kommer viewas varje frame (t.ex bomb eller UI) så borde den vara i Update?

2021-04-29 17:37 UTC, olchyk98 commented on Assets/Scripts/Timer.cs
> +    private void Update()
FixedUpdate använder man när man sysslar me nåt exakt. Nåt som uppdateras oberoende av fps och sånt. Tex fysik eller tid

2021-04-29 17:39 UTC, k0ded commented on Assets/Scripts/Player/PlayerLook.cs
> +            _rigidbody.angularVelocity = Vector3.zero;
för att shittet kallas varje gång man rör musen. blir lite onödigt att hämta Rigidbody varje gång man rör musen :)

2021-04-29 17:43 UTC, olchyk98 commented on Assets/Scripts/Timer.cs
> +    private void Update()
Spelar ingen roll i detta fallet
De ba räcknas good praktik att sätta sånt skit i fixed bram ![image](https://user-images.githubusercontent.com/40524044/116594975-1834e000-a923-11eb-80ff-957b772e03cf.png)

2021-04-29 18:09 UTC, olchyk98 approved these changes

2021-04-30 07:23 UTC, trilleplay approved these changes
LETS GO

2021-04-30 07:23 UTC, merged