SoundFX/PaintingPuzzle
olchyk98/deadmind pull request #36
Opened 2021-05-07 08:59 UTC by HugoLandin

SoundFX in assets, PaintingPuzzle in prefabs

2021-05-07 09:13 UTC, trilleplay requested changes

2021-05-07 09:13 UTC, trilleplay commented on Assets/Painting.cs
> +        light.range = (Convert.ToInt32(paintingManager.selectedPainting == this)*3);
wtf

2021-05-07 10:53 UTC, olchyk98 requested changes

2021-05-07 10:53 UTC, olchyk98 commented on Assets/Painting.cs
> +    PaintingManager paintingManager;
private

2021-05-07 10:53 UTC, olchyk98 commented on Assets/Painting.cs
> +    public Light light;
uh?

2021-05-07 10:53 UTC, olchyk98 commented on Assets/Painting.cs
> +    public MeshRenderer paintingRenderer;
should it be pub?
If the answer is yes then PaintingRenderer

2021-05-07 10:53 UTC, olchyk98 commented on Assets/Painting.cs
> +    private void Awake()
start?

2021-05-07 10:53 UTC, olchyk98 commented on Assets/PaintingManager.cs
> +    Painting[] paintings;
private
_paintings

2021-05-07 10:56 UTC, HugoLandin commented on Assets/PaintingManager.cs
> +    int correctPaintingIndex;
k0ded will solve that later

2021-05-07 10:57 UTC, olchyk98 commented on Assets/Painting.cs
> +    public MeshRenderer paintingRenderer;
ok.
but rename
all public fields should start with a capital letre

2021-05-07 10:58 UTC, olchyk98 commented
@trilleplay det kommer att ta 200 år för att rebasea. GJ

![https://www.iheartradio.ca/image/policy:1.14693857:1614780520/dababy.jpg?a=16%3A9&w=1000&$p$a$w=7782016](https://www.iheartradio.ca/image/policy:1.14693857:1614780520/dababy.jpg?a=16%3A9&w=1000&$p$a$w=7782016)

2021-05-07 10:58 UTC, olchyk98 commented on Assets/PaintingManager.cs
> +    int correctPaintingIndex;
okay, `private int correctPaintingIndex ` for now

2021-05-11 11:16 UTC, olchyk98 commented
very gud peAr i recommend

2021-05-12 13:08 UTC, merged